-- Fintech Risk & Fraud Database Schema

-- 1. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    customer_id INTEGER PRIMARY KEY AUTOINCREMENT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    credit_score INTEGER NOT NULL CHECK (credit_score >= 300 AND credit_score <= 850),
    annual_income REAL NOT NULL CHECK (annual_income >= 0),
    employment_years INTEGER NOT NULL CHECK (employment_years >= 0),
    debt_amount REAL NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Loan Applications Table
CREATE TABLE IF NOT EXISTS loan_applications (
    application_id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_id INTEGER NOT NULL,
    loan_amount REAL NOT NULL CHECK (loan_amount > 0),
    term_months INTEGER NOT NULL CHECK (term_months IN (12, 24, 36, 48, 60)),
    loan_purpose TEXT NOT NULL,
    interest_rate REAL NOT NULL,
    dti_ratio REAL NOT NULL, -- Debt to Income Ratio
    risk_score REAL NOT NULL, -- Probability of default generated by model (0.0 to 1.0)
    decision_status TEXT NOT NULL CHECK (decision_status IN ('APPROVED', 'REJECTED', 'PENDING_REVIEW')),
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

-- 3. Transactions Table (for fraud/anomaly detection)
CREATE TABLE IF NOT EXISTS transactions (
    transaction_id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_id INTEGER NOT NULL,
    amount REAL NOT NULL,
    merchant_category TEXT NOT NULL,
    location TEXT NOT NULL,
    transaction_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_fraud_flag INTEGER DEFAULT 0 CHECK (is_fraud_flag IN (0, 1)),
    anomaly_score REAL DEFAULT 0,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_loan_app_customer ON loan_applications(customer_id);
CREATE INDEX IF NOT EXISTS idx_transactions_customer ON transactions(customer_id);
CREATE INDEX IF NOT EXISTS idx_transactions_fraud ON transactions(is_fraud_flag);
